clean_build: true
retain_objc_accessible: true
retain_public: true
schemes:
- Infomaniak Mail
- MailAppIntentsExtension
- MailCore
- MailCoreUI
- MailNotificationServiceExtension
- MailResources
- MailShareExtension
targets:
- Infomaniak Mail
- MailAppIntentsExtension
- MailCore
- MailNotificationServiceExtension
- MailResources
- MailShareExtension
workspace: Mail.xcworkspace
