name: NEW Euria Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    name: Euria code Review
    steps:
      - name: Euria code Review
        uses: adrien-coye/genai-code-review@ab5c1ac0725162390c5d1ac9fea08e31b96cd07a
        with:
          openai_api_key: ${{ secrets.EURIA_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "moonshotai/Kimi-K2.5"
          openai_temperature: 0.3
          mode: files
          language: en
          custom_prompt: "" # optional
        env:
          OPENAI_BASE_URL: "https://api.infomaniak.com/2/ai/27/openai/v1"