name: Build and Upload on AppStoreConnect

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Upload on AppStoreConnect
    runs-on: [ self-hosted, iOS ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: jdx/mise-action@v2
        with:
          cache: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup AppStoreConnect API key
        env:
          API_KEY_ID: ${{ secrets.APPSTORECONNECT_API_KEY_ID }}
          API_KEY: ${{ secrets.APPSTORECONNECT_API_KEY }}
        run: |
          mkdir -p private_keys
          touch "private_keys/AuthKey_$API_KEY_ID.p8"
          echo -e "$API_KEY" > "private_keys/AuthKey_$API_KEY_ID.p8"
      - name: Build and upload
        env:
          WORKSPACE: "Mail.xcworkspace"
          SCHEME: "Infomaniak Mail"
          SENTRY_PROJECT: "mail-ios"
          API_ISSUER_ID: ${{ secrets.APPSTORECONNECT_API_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.APPSTORECONNECT_API_KEY_ID }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        run: ./scripts/build_and_upload.sh $GITHUB_REF_NAME
      - name: Cleanup
        if: always()
        run: rm -rf ./private_keys
